### ISSUE TITLE
Extension is not working on chrome 130

### ISSUE THREAD

**Issue by Herobread** [Herobread/better-studres-v2#101]
### Description
Some content policy issue

content-script-loade…7h9za-DvBTOSDf.js:7 Refused to load the script 'chrome-extension://366cb80a-4f93-453e-9309-fe671ec88018/assets/index.tsx-a6v7h9za.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### Screenshots
![image](https://github.com/user-attachments/assets/a813c883-4f0c-4079-a774-1c963e8e7570)

**Comment by Herobread** [comment]
![image](https://github.com/user-attachments/assets/b432671a-8599-4e2f-a262-c3b7cfa5dc36)

**Comment by Herobread** [comment]
```
(function () {
  'use strict';

  (async () => {
    await import(
      /* @vite-ignore */
      chrome.runtime.getURL("assets/index.tsx-a6v7h9za.js")
    );
  })().catch(console.error);

})();
```

in bundle content-script-loader.index.tsx-a6v7h9za-DvBTOSDf.js

**Comment by Herobread** [comment]
https://github.com/crxjs/chrome-extension-tools/issues/918

**Comment by Herobread** [comment]
added temporary workaround for build 

https://github.com/Herobread/better-studres-v2/commit/33396cc2874606ba44cea6a699956b0cb270281b

**Comment by cherfaoui-syphax** [comment]
> added temporary workaround for build
> 
> [33396cc](https://github.com/Herobread/better-studres-v2/commit/33396cc2874606ba44cea6a699956b0cb270281b)

Thank you so much , this worked for me

**Comment by Herobread** [comment]
https://github.com/Herobread/better-studres-v2/pull/103

now it's possible to just update to the new version of crxjs
