### ISSUE TITLE
White button in dark-mode

### ISSUE THREAD

**Issue by YehorBoiar** [Herobread/better-studres-v2#62]
![image](https://github.com/user-attachments/assets/fc0cea85-f578-4db4-a742-e278454dcab4)

**Comment by Herobread** [comment]
you are using one of test builds, that's why there is that strange button

switch from dev build to latest version from [chrome web store](https://chromewebstore.google.com/detail/better-studres/kamnhbpjhhhjlbandgpngdnplledombg)
