### ISSUE TITLE
Add Murray's Polygon bg

### ISSUE THREAD

**Issue by YehorBoiar** [Herobread/better-studres-v2#87]
### Description

Would've been nice to add that polygon on bg

**Comment by Herobread** [comment]
Not sure, I tried to add, but it feels like really forced addition

Few concepts:
![image](https://github.com/user-attachments/assets/a76adb68-d66d-44b6-a8c4-6383b505da5f)
![image](https://github.com/user-attachments/assets/b22f20de-4dc4-4ea7-addd-6824dffaf407)
![image](https://github.com/user-attachments/assets/8a432e38-b19b-4790-a2a1-89c07a10ee27)

**Comment by YehorBoiar** [comment]
Perhaps you're right. You could try to add some shadows to make it less flat though.

**Comment by Herobread** [comment]
It makes it much less minimal, which is the opposite of main design idea, so this won't be added
